export const QUESTIONS = {
  beginner: [
    "What is your absolute favorite food, and can you describe the first time you tasted it or a special memory you have eating it?",
    "If you could change one thing about your daily routine to make your day more exciting, what would it be and why?",
    "Tell me about the last movie you watched that made you feel a strong emotion. What happened in the story?",
    "Think about your best friend. What is one personality trait they have that you wish you also had yourself?",
    "If you had a completely free Saturday with no responsibilities, how would you spend every hour of that day?",
    "Describe your favorite room in your house in detail. What makes it feel comfortable or special to you?",
    "Which season of the year do you think is the most beautiful, and what are three things you love doing during that time?",
    "If you could travel to any country in the world tomorrow for free, where would you go and what is the first thing you would see?",
    "What is a color that represents your personality, and can you give an example of a time you felt that way?",
    "Think of a fun memory from when you were a child. Why does that specific moment stay in your mind after all these years?",
    "If you could communicate with any animal for one day, which animal would you choose and what would you ask them?",
    "Do you prefer the calm of a morning tea or the energy of a morning coffee? Describe how it helps start your day.",
    "Look out the window and describe the weather today as if you were telling someone who has never seen it before.",
    "Talk about a hobby you have. How did you first get interested in it, and how does it make you feel when you are practicing it?",
    "Think of a song you can't stop listening to. What do you think the lyrics are trying to say, or how does the melody make you feel?",
    "Who is a person in your life that you admire the most? What is one specific thing they did that earned your respect?",
    "If you had to recommend one book to a stranger to help them understand you better, which book would it be and why?",
    "Describe a meal you had recently that was so good you wanted to share it with everyone. What made it so delicious?",
    "What is your perfect breakfast, and how does the atmosphere of the morning change when you have it?",
    "Describe your favorite piece of clothing. Does it have a history, or is there a reason you feel more confident when wearing it?",
    "Talk about a sport or physical activity you enjoy. What is the most difficult part of it, and how do you stay motivated?",
    "What is the most meaningful holiday in your culture, and how do you and your family specifically celebrate it each year?",
    "Describe a park or a natural place you've visited. What are the sounds, smells, and sights that made it memorable?",
    "What is the most thoughtful gift you have ever received, and why did it mean more to you than something expensive?",
    "Talk about a skill you have that not many people know about. How did you learn it, and why is it important to you?",
    "What is one thing you would change about your school or workplace to make everyone there feel more inspired?",
    "Describe a typical family dinner in your house. Who does most of the talking, and what are the usual topics of conversation?",
    "If you could only use one way to travel for the rest of your life (walking, flying, driving), which would you pick and why?",
    "Think of a fruit or vegetable you hated as a child but love now. What changed about your taste or perspective?",
    "Describe a moment in the last week where you felt truly at peace. What were you doing and who were you with?",
    "What is your favorite thing to do when it's raining outside? How does the sound of the rain change your mood?",
    "If you could design the perfect pet, what would it look like and what kind of personality would it have?",
    "What was your favorite game to play when you were younger? Can you explain the rules and why you loved it so much?"
  ],
  intermediate: [
    "Tell me about a time you worked in a team where things weren't going well. How did you help the group get back on track?",
    "If you could achieve any professional goal in the next five years, what would it be, and what is the very first step you need to take?",
    "When you are facing a high-pressure situation, what is your internal process for staying calm and making the right decision?",
    "Describe a major challenge you overcame recently. If you had to face it again, what would you do differently based on what you learned?",
    "In your opinion, is it more important for a leader to be liked by their team or to be respected for their decisions? Why?",
    "Think about how technology has changed your life in the last five years. Is there any part of 'old life' that you actually miss?",
    "Who is a person that significantly influenced your career or life path? What was the most important piece of advice they ever gave you?",
    "Do you think social media brings people closer together or creates more distance between us? Give a specific example from your life.",
    "Describe a project or achievement you are proud of. What was the most difficult obstacle you hit during the process?",
    "How do you keep yourself motivated on a Tuesday afternoon when you have a lot of boring work to do? What's your secret?",
    "If someone was hesitant about learning your native language, how would you convince them that it's worth the effort?",
    "Think of a cultural tradition you participate in. If you had to explain its deep meaning to someone from another planet, what would you say?",
    "How do you decide when to stop working and start living your personal life? Is 'balance' something you actually achieve or just chase?",
    "Many people say that 'happiness is a choice.' Do you agree with this, or do you think our environment plays a bigger role?",
    "Describe a place you visited that felt completely different from anywhere else. What was the most surprising thing about the local culture?",
    "If you were forced to spend your next holiday alone in a cabin with no internet, how would you keep yourself entertained and happy?",
    "What is a piece of news or a scientific discovery you heard recently that made you rethink something you thought was true?",
    "Talk about a mistake you made that felt like a disaster at the time. How do you look back on that same mistake today?",
    "What are the three most important qualities a person must have for you to consider them a true, lifelong friend?",
    "If you could send a 30-second message to yourself ten years in the future, what would you say and why?",
    "Think of a movie or a book that made you completely change your mind about a certain group of people or a social issue.",
    "What is the best piece of advice you ever ignored? Looking back, why did you ignore it, and what happened as a result?",
    "Describe the last time you stepped far out of your comfort zone. What was the physical sensation of that fear, and how did it feel afterward?",
    "Some people define success by money, others by impact. How do you personally measure if you've had a 'successful' day?",
    "If you had to move to a very small, quiet village after living in a big city, what is the one thing you would miss the most?",
    "Think of a historical figure you find fascinating. If you could have dinner with them, what is the one question you'd be dying to ask?",
    "How do you manage your time when you have five different things that all feel like 'top priority'? How do you choose what to do first?",
    "Is there a specific genre of music that you used to dislike but now appreciate? What caused that shift in your perspective?",
    "Think of a goal you reached recently. Who is the first person you told, and why was their reaction important to you?",
    "How do you prefer to receive 'tough' feedback? Do you want it straight and blunt, or do you prefer a more gentle approach?",
    "If you could relive one perfect day from your past exactly as it happened, which day would you choose and why?",
    "What is the most important lesson you've learned from a person who was much younger or much older than you?",
    "If you could master any difficult skill instantly—like playing a complex instrument or a new language—how would it change your life?"
  ],
  advanced: [
    "Describe a high-stakes situation where you had to make a critical decision with almost no data. What was your 'gut feeling' telling you?",
    "In a world where AI is becoming more human-like, what do you think is the one 'voice' or 'trait' that will always remain uniquely human?",
    "How do you maintain your personal brand and professional integrity in an environment that rewards quick wins over long-term quality?",
    "Discuss the ethical trade-offs we make for convenience. Is the modern world making us more connected or just more distracted?",
    "Describe a time you had to lead a team through a period of deep uncertainty. How did you keep them focused when you didn't have all the answers?",
    "If you were in charge of the education system, what is the one 'human skill' you would make mandatory for every student to learn?",
    "How do you handle the emotional 'hangover' of a major professional failure? What is your specific ritual for getting back into the game?",
    "Do you think emotional intelligence can be taught, or is it something we are born with? How have you seen it impact a project's success?",
    "Describe a complex problem you solved where the 'obvious' solution failed. How did you convince others to try your unconventional idea?",
    "In the age of digital transparency, is true privacy still possible, or have we already traded it away for the benefits of the internet?",
    "How do you navigate a situation where your personal values are in direct conflict with a professional requirement or a client's request?",
    "Think of a time you were under extreme pressure and made a mistake. How did you take ownership of it without losing your authority?",
    "What is the most significant shift you've seen in your field of work in the last year, and how are you specifically adapting to it?",
    "Discuss the concept of 'cultural homogenization.' Is the world becoming too similar, and what are we losing as a result?",
    "How do you foster a culture of radical honesty in a team where people are afraid of hurting feelings or being judged?",
    "Describe a conflict you managed between two high-performing individuals. How did you find a middle ground that didn't compromise the work?",
    "Is the idea of 'work-life balance' a dangerous myth that makes us more stressed, or is it a target we should all be hitting?",
    "Discuss the role of intuition versus logic in your life. Can you think of a time when logic failed you but your intuition was correct?",
    "If you had to start your entire career over from scratch tomorrow in a completely different industry, what is the first thing you'd do?",
    "What do you think is the most dangerous invention of the last century, and do you think we have the power to control its impact?",
    "How do you ensure that your message is not just heard, but truly understood when speaking to a group with completely different backgrounds?",
    "Discuss the difference between 'being busy' and 'being productive.' How do you audit your own time to ensure you're doing the right things?",
    "What is a vision you have for your industry ten years from now? What role do you see yourself playing in that future landscape?",
    "Think of the most difficult feedback you've ever received. Was it the content of the feedback or the person giving it that made it so hard?",
    "How has your definition of 'ambition' changed as you've gotten older? Is it still about reaching the top, or is it about something else?",
    "Discuss how you measure the success of your life outside of career or financial achievements. What are your 'KPIs' for a good life?",
    "Describe a time you took a risk that everyone else said was a bad idea. What did you see that they didn't, and what was the outcome?",
    "Do you believe that remote work has permanently damaged our ability to build deep professional relationships? Why or why not?",
    "Discuss the relationship between suffering and growth. Can we reach our full potential without experiencing significant hardship?",
    "In a world of constant digital noise, how do you protect your deep focus? What are the physical and mental boundaries you set?",
    "Describe a time you mentored someone who was difficult to reach. How did you break through, and what did you learn about your own style?",
    "What is the most profound realization you've had about your own ego in the last year? How has it changed how you interact with others?",
    "If you could be remembered for only one sentence or one specific idea, what would you want that to be for the next generation?"
  ]
};
